apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed 
  labels:
    app: feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
        - name: feed
          image: mahaba98/udagram-api-feed:v1
          envFrom:
            - secretRef:
                name: udagram-env-secret
            - secretRef:
                name: udagram-aws-secret
            - configMapRef:
                name: udagram-configmap
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
