apiVersion: v1
kind: Secret
metadata:
  name: udagram-aws-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQVlXVExUSjRPR1RBVlhQNDQ=
  AWS_SECRET_ACCESS_KEY: SzBTYlBrSGt5M0I2SXA3SlE1T21NMEtmRFV1ZDdHb2xnaWw2aFp6Mg==
  AWS_SESSION_TOKEN: RndvR1pYSXZZWGR6RUdjYURPMDVsWGtCR281bWtKbFg4aUxWQWR6bDZqUFZHMEpvM1MrSnNFZWJMekRhWTJpakRwZWNaQU13U0JjcDhoQmVNeTFrQmpycHljL0ptTk1FV0NIVUFHYm95MjF5c2grSCtUaWRqYW9xcm9yYUQvMzc1MElFc1plcU55aC80clViT1ZVbEM3ZDQ2RXF5RDQ0T0FWWFpsMFRrN3NvY2xNd0tNcUwvRmlyaER0UFpoUjl0NFpJWXl6OS9EQlQ2VDcrckZ6aHVmWXQ1bzlzd24rZ0dsTVpRUU5Sd3VyNGhVaXgwazJLS2w4eXpGZmJ5Z2YxUGxwcEtFODBYZEUxMGpiMG1hc3JLSHh5WDNRZmhVSVowK0MwMHhiVnlINzZZN2hDc01pclc4eUoyd3pubnJzOGxneWk5dUlLYUJqSXR2MWRDTnFaL3RnaFBEZ3MrWHQ5R3ZabUVLVnRFN29zUFhFM2xTVm5yeisyQk9tRnc2alVvL3ZMRUorRGU=
