version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
      dockerfile: Dockerfile
    image: mahaba98/reverseproxy:v1
  backend_user:
    build:
      context: ./udagram-api-user
      dockerfile: Dockerfile
    image: udagram-api-user:v1
  backend_feed:
    build:
      context: ./udagram-api-feed
      dockerfile: Dockerfile
    image: udagram-api-feed:v1
  frontend:
    build:
      context: ./udagram-frontend
      dockerfile: Dockerfile
    image: mahaba98/udagram-frontend:v1
