apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: udagram-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend-deployment
  template:
    metadata:
      labels:
        app: udagram-frontend-deployment
    spec:
      containers:
        - name: udagram--deployment
          image: mahaba98/udagram-frontend:v1
          envFrom:
            - secretRef:
                name: udagram-env-secret
            - secretRef:
                name: udagram-aws-secret
            - configMapRef:
                name: udagram-configmap
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
